# Generated by Django 5.2.5 on 2025-09-20 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinc_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='Department_image',
            field=models.FileField(default=2, upload_to='Department_image/'),
            preserve_default=False,
        ),
    ]
