# Generated by Django 5.2.5 on 2025-09-30 07:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinc_app', '0002_department_department_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='doctor_shedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='clinc_app.doctor')),
            ],
        ),
    ]
