# Generated by Django 5.2.5 on 2025-10-07 08:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinc_app', '0003_doctor_shedule'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookingAppointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('statusFiled', models.IntegerField(default=0)),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='clinc_app.doctor')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='clinc_app.patient')),
                ('scheduleTime', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='clinc_app.doctor_shedule')),
            ],
        ),
    ]
